#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy initial conditions
cp -rf 0.org 0

# Set turbine parameters
python scripts/set_turbines.py "$@"

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication topoSet

if [ "$1" = "-parallel" ]
    then
    nProc=$(getNumberOfProcessors)
    runApplication decomposePar
    ls -d processor* | xargs -I {} rm -rf ./{}/0
    ls -d processor* | xargs -I {} cp -r 0.org ./{}/0
    runParallel pimpleFoam  $nProc
    runApplication reconstructPar
    rm -rf processor*
else
    runApplication pimpleFoam
fi

runApplication vorticity
scripts/Allrun.post
